### ISSUE TITLE
What do you think about man page for nodelint?

### ISSUE THREAD

**Issue by Sannis** [tav/nodelint#10]

**Comment by tav** [comment]
Nice idea. However I haven't touched troff in about 10 years. Care to take a lead on this?

**Comment by Sannis** [comment]
Yep, i'll write it soon. [Ronn.js](http://github.com/kapouer/ronnjs/) help me with this.

Example from nodeunit project: http://github.com/Sannis/nodeunit/blob/master/doc/nodeunit.md (not merged yet). For nodelint man page I will also include JSLint options description.

**Comment by tav** [comment]
Wicked — thanks Sannis!

**Comment by Sannis** [comment]
I've pulled it to you: http://github.com/tav/nodelint/pull/12.

**Comment by tav** [comment]
Cheers Sannis — I've merged it and also made a few changes to hopefully make it even clearer...

**Comment by Sannis** [comment]
Thanks. So much nicer to read :-)
