### ISSUE TITLE
Node standards?

### ISSUE THREAD

**Issue by jpolo** [tav/nodelint#11]
I just downloaded the jslint package. Although I found it very useful, I think the executable should be named "node-lint" instead of "nodelint".
It is just a standard improvement but it is still important as jslint itself is created to define some standards for javascript (node based executable are named node-waf, node-repl, etc).

**Comment by tav** [comment]
Interesting examples. What does everyone else think?

**Comment by Sannis** [comment]
As Ryan says, `node-repl` would be gone away in v0.3. So we will have `node`, `node_g` and `node-waf`. I don't think, than there is some kind of standatd to name executables written in node as `node-*`. As well there isn't any rules for modules names, only to supress prefix in package.json. Executable name doesn't matter, I think.

I also list my /usr/bin and found example groups of executables with both `xyz-`, `xyz_` and `xyz` prefixes.

**Comment by jpolo** [comment]
Ok but maybe node_g shouldn't be named node_g too :)
I still think that naming differently foobar, foo_bar, foo-bar is not good. I proposed the "-" separator because it is used by well known commands (ex: apt-get, ...)

Talking about the prefix, it maybe an interesting improvement for a better distribution on npm. How to name it? lint? jslint?

In my opinion, I prefer just "lint" because the "js" is implied by the language we're using...

**Comment by Sannis** [comment]
> I proposed the "-" separator because it is used by well known commands (ex: apt-get, ...)

I think this is holywar theme :-) I'm using openSUSE and there is part of my /usr/bin:
With "-":
    -rwxr-xr-x  97116 2010-07-06 05:58 bluetooth-applet
    -rwxr-xr-x  88956 2010-07-06 05:58 bluetooth-properties
    -rwxr-xr-x  68180 2010-07-06 05:58 bluetooth-sendto
    -rwxr-xr-x  80376 2010-07-06 05:58 bluetooth-wizard

Without anything (I think this programs are more close to you environment):
    -rwxr-xr-x  50389 2010-07-05 23:27 debchange
    -rwxr-xr-x  28787 2010-07-05 23:27 debcheckout
    -rwxr-xr-x   5818 2010-07-05 23:27 debclean
    -rwxr-xr-x  24120 2010-07-05 23:27 debcommit
    -rwxr-xr-x  32360 2010-07-05 23:27 debdiff
    -rwxr-xr-x  16114 2010-07-05 23:27 debi
    -rwxr-xr-x   5668 2010-07-05 23:28 debpkg
    -rwxr-xr-x  10693 2010-07-05 23:27 debrelease
    -rwxr-xr-x   5347 2010-07-05 23:27 deb-reversion
    -rwxr-xr-x    823 2010-07-05 23:27 debrsign
    -rwxr-xr-x   2155 2010-07-05 23:27 debsign
    -rwxr-xr-x   8517 2010-07-05 23:27 debsnap
    -rwxr-xr-x  46417 2010-07-05 23:27 debuild

With "_" and without anything at second words join (holy shit):
    -rwxr-xr-x   8336 2010-07-05 23:27 dh_install
    -rwxr-xr-x   3184 2010-07-05 23:27 dh_installcatalogs
    -rwxr-xr-x   4629 2010-07-05 23:27 dh_installchangelogs
    -rwxr-xr-x   1616 2010-07-05 23:27 dh_installcron
    -rwxr-xr-x   2536 2010-07-05 23:27 dh_installdeb
    -rwxr-xr-x   3235 2010-07-05 23:27 dh_installdebconf
    -rwxr-xr-x   1628 2010-07-05 23:27 dh_installdirs

More significant of argument: "-" in the package name is usual used as a namespace separator. But nothing prevents the product to have a name, which historically different. For example: JSLint. So the Node.js code checking tools had been named NodeLint.

**Comment by mkitt** [comment]
I don't really have an opinion on this. It seems like a good deal of the projects within npm are all over the place, some using "-", "_" or just one liners like nodelint, nodeunit... Seems like this might be a better question for @issacs or the node community in general? I'd lean towards not changing until a defined standard has been adopted though.

**Comment by Sannis** [comment]
> Seems like this might be a better question for @issacs or the node community in general?

Sounds good, I think we should debate about this in maillist rather that "one separate script issue".

**Comment by jpolo** [comment]
It seems a good idea. I don't know exactly how you planned to contact him/them (googlegroups, etc). If it is some kind of forum, googlegroups or assimilate could you copy/paste the link? I will just close this topic and keep participating on this new node community discussion.

Thx

**Comment by Sannis** [comment]
There is the googlegroups for users (http://groups.google.com/group/nodejs/topics) and Node.js core developers (http://groups.google.com/group/nodejs-dev/topics).

**Comment by jpolo** [comment]
Ok thanks Sannis, I posted this morning a topic and it's waiting for moderation.

**Comment by jpolo** [comment]
Here is the link to the topic:
http://groups.google.com/group/nodejs/browse_thread/thread/f9d941808326fb3c/9be0222efbeccf45#9be0222efbeccf45
