### ISSUE TITLE
nodelint directory/ or nodelint directory/*

### ISSUE THREAD

**Issue by niklasf** [tav/nodelint#15]
I can't use
    nodelint lib/ tests/
as suggested by the documentation in README.md.
Yet I can use
    nodelint lib/\* tests/*

This is the output:

```
Error: Opening file <lib/>
Error: EISDIR, Is a directory

Error: Opening file <tests/>
Error: EISDIR, Is a directory

0 errors
```

Am I doing something wrong?

**Comment by Sannis** [comment]
Are you using last nodelint from repo? In this case, please, tell us about you Node.js version (but I think it doesn't matter).

**Comment by niklasf** [comment]
I've installed it using npm.
Version number is 0.4.0 and it could very well not be the current state of the repository. So thank you and _Close_.
