### ISSUE TITLE
Update the version on npmjs.org

### ISSUE THREAD

**Issue by cliffano** [tav/nodelint#16]
The version of nodelint published on npmjs.org is outdated, can someone with access please publish the latest version?

Thanks.

**Comment by Sannis** [comment]
I think only Tav can do this.

**Comment by cliffano** [comment]
Is Tav M.I.A?

**Comment by Sannis** [comment]
I think so. I and mkitt can operate with this repository and I can merge all my updates, but we can't publish new nodelint versions to npm without Tav :(

**Comment by cliffano** [comment]
Oleg, I think you have been added to the owner list of nodelint. Would you do the honor of publishing the latest to npmjs when you get the chance? (no rush).

As per the email discussion, isaac also added me, but I think it's better for you, tav, and mtkitt to be the real owners.
I don't mind helping out as a back up if there's any need in the future :).

**Comment by paularmstrong** [comment]
+1! It'd be really great to have this actually up to date.

**Comment by Sannis** [comment]
I've merged my updates and fix into master and also cherry-pick [this](https://github.com/clebert/nodelint/commit/61c438340ea168f857bce67677dc9a69efa81121). I plan to write brief changelog, increase version to 0.5.0 and than publish it to npm in next days. If you have some remarks for default config values, your are wellcome.
