### ISSUE TITLE
Move reporters to lib/reporters and expose nodelint --{name}-reporter option for each

### ISSUE THREAD

**Issue by Sannis** [tav/nodelint#21]
Start of discussion: https://github.com/tav/nodelint/pull/20

**Comment by Sannis** [comment]
@mkitt, are we need keep both elaborate.js and syntastic-reporter.js for vim?

**Comment by mkitt** [comment]
I don't think so. I believe they are in there as just examples for users who might be interested in integrating into an editor or creating a reporter. Feel free to blow them away.

**Comment by Sannis** [comment]
Thanks for quick response. I'll try to use default and these reporters with vim and remove duplicates.

**Comment by Sannis** [comment]
I'l keep both TextMate reporters with their names.

**Comment by Sannis** [comment]
I've rebase by fork to make commits history more clean. All tests passes (http://travis-ci.org/#!/Sannis/nodelint/builds), reporters moved to lib/reporters and available by reporter name or by filename.

**Comment by Sannis** [comment]
@cliffano: Now built-in reporters available with --reporter=name (f.e. --reporter=xml), so does it necessary to have --xml-reporter cli option?

**Comment by cliffano** [comment]
Sorry for late reply. Nope, happy with the --reporter=name approach :). Thanks for adding it.

**Comment by Sannis** [comment]
No problems :) I was a little sick, so it will not finished until next week.

**Comment by Sannis** [comment]
Merged.
