### ISSUE TITLE
ARGV error on node 0.5.10

### ISSUE THREAD

**Issue by yuroller** [tav/nodelint#26]
I had to modify line 171 of nodelint as the following to make it run under node 0.5.10.
params = (process.ARGV || process.argv).splice(2);

**Comment by Sannis** [comment]
Which version (or commit hash) of nodelint are you using?

**Comment by yuroller** [comment]
2011/11/2 Oleg Efimov
reply@reply.github.com:

> Which version (or commit hash) of nodelint are you using?

nodelint 0.5.1.
I installed it a few minutes ago with: npm install nodelint

## 

Yuri Valentini

**Comment by Sannis** [comment]
Ok. This bug was already fixed in 4004b019cff24dbb98e90c9317dc992dd6fbb80e and I'm waiting for 0.6.x to publish new nodelint version.

**Comment by Sannis** [comment]
Nodelint v0.5.2 with node 0.6 support just published.
