### ISSUE TITLE
Wrong 'undef' option description and default value

### ISSUE THREAD

**Issue by allait** [tav/nodelint#28]
Since version 0.5 `nodelint` doesn't show missing `var` in declarations and use of undeclared variables as errors by default. This is due to the `true` default value of `undef` configuration option.

JSLint.com instructions say that `undef` should be "true if variables and functions need not be declared before used", but `config.js` gives the opposite definition:

```
"undef"      : true,  // if variables should be declared before used
```

**Comment by Sannis** [comment]
Thanks, Alex!
