### ISSUE TITLE
Nodelint reporters make no difference to output

### ISSUE THREAD

**Issue by nelstrom** [tav/nodelint#30]
Nodelint could be the commandline interface to JSLint that I've been looking for. The reporters feature sets it apart from the other tools I've looked at (e.g. https://github.com/reid/node-jslint), but so far I been unable to make them work. I wonder if you can help?

I'm using this snippet of JS as a test:

```
var i;
for (i=1; i <= 100; i++) {
    if(i % 15 == 0) {
        console.log('Fizzbuzz');
    } else if(i % 5 == 0) {
        console.log('Buzz');
    } else if(i % 3 == 0) {
        console.log('Fizz');
    } else {
        console.log(i);
    }
};
```

If I run nodelint without specifying a reporter, I get the following output:

```
nodelint fizzbuzz.js
The "sys" module is now called "util". It should have a similar interface.
/Users/drew/code/nodelint/fizzbuzz.js, line 2, character 22: Unexpected '++'.
for (i=1; i <= 100; i++) {
/Users/drew/code/nodelint/fizzbuzz.js, line 3, character 15: Expected '===' and instead saw '=='.
if(i % 15 == 0) {
/Users/drew/code/nodelint/fizzbuzz.js, line 5, character 21: Expected '===' and instead saw '=='.
} else if(i % 5 == 0) {
/Users/drew/code/nodelint/fizzbuzz.js, line 7, character 21: Expected '===' and instead saw '=='.
} else if(i % 3 == 0) {
/Users/drew/code/nodelint/fizzbuzz.js, line 12, character 2: Unexpected ';'.
};
5 errors
```

I get exactly the same output if I include `--reporter lib/reporters/vim.js`, and the same goes for all of the reporters that are bundled in the `nodelint/lib/reporters` directory. Here's an example of the output. I've included the command line that I entered, so you can see if I'm doing anything wrong:

```
nodelint fizzbuzz.js --reporter lib/reporters/vim.js 
The "sys" module is now called "util". It should have a similar interface.
/Users/drew/code/nodelint/fizzbuzz.js, line 2, character 22: Unexpected '++'.
for (i=1; i <= 100; i++) {
/Users/drew/code/nodelint/fizzbuzz.js, line 3, character 15: Expected '===' and instead saw '=='.
if(i % 15 == 0) {
/Users/drew/code/nodelint/fizzbuzz.js, line 5, character 21: Expected '===' and instead saw '=='.
} else if(i % 5 == 0) {
/Users/drew/code/nodelint/fizzbuzz.js, line 7, character 21: Expected '===' and instead saw '=='.
} else if(i % 3 == 0) {
/Users/drew/code/nodelint/fizzbuzz.js, line 12, character 2: Unexpected ';'.
};
5 errors
```

I have the latest versions of node and nodelint installed, as follows:

```
node:     0.6.7
nodelint: 0.5.2
```

Do you have any idea what might be causing this?

Thanks,
Drew

**Comment by Sannis** [comment]
This is my fail. Please give me a link to page with such usage example.

Nodelint v0.5.2 can use two kinds of reporters: build-in and any other. If you want to use built-in VIM reporter you should run just:

```
nodelint --reporter=vim ./path/to/your/file.js
```

Full list of built-in reporter are available by:

```
nodelint --list-reporters
```

So in you example nodelint tries to use lib/reporters/vim.js from your current folder, which does not exists.

**Comment by nelstrom** [comment]
I've tried doing as you suggest with `--reporter=vim`. It reported `no such file or directory '--reporter=vim'`:

```
nodelint --reporter=vim ./fizzbuzz.js
The "sys" module is now called "util". It should have a similar interface.

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: ENOENT, no such file or directory '--reporter=vim'
    at Object.statSync (fs.js:414:18)
    at /usr/local/lib/node_modules/nodelint/nodelint:183:17
    at Array.forEach (native)
    at /usr/local/lib/node_modules/nodelint/nodelint:157:10
    at Object.<anonymous> (/usr/local/lib/node_modules/nodelint/nodelint:200:1)
    at Module._compile (module.js:432:26)
    at Object..js (module.js:450:10)
    at Module.load (module.js:351:31)
    at Function._load (module.js:310:12)
    at Array.0 (module.js:470:10)
```

Am I doing something wrong?

> Please give me a link to page with such usage example

Sorry, but there's nothing else I can link to, besides the example here.

**Comment by Sannis** [comment]
Please try 0.6.0 from npm, I've just update it.

**Comment by nelstrom** [comment]
You star! That works now for me too.

**Comment by Sannis** [comment]
Sorry for late update :-|
