### ISSUE TITLE
Suppress ANSI colors

### ISSUE THREAD

**Issue by nelstrom** [tav/nodelint#32]
Out of the box, and using the default formatter, nodelint uses ANSI colors to mark error messages red in the console. It would be great if there was a way to suppress these. Two ideas spring to mind:
- provide a `--nocolor` flag
- and/or respect the `NODE_DISABLE_COLORS` environment variable

I'm not sure which is the best approach, but I've found similar issues filed for [coffeescript](https://github.com/jashkenas/coffee-script/pull/1757) and [cli](https://github.com/chriso/cli/issues/28).

**Comment by Sannis** [comment]
I think respect the `NODE_DISABLE_COLORS` is a good suggestion.

**Comment by Sannis** [comment]
Only default reporter use ANSI coloring, so I move options to reporter and add NODE_DISABLE_COLORS check there.

Is it ok for you, @nelstrom?

**Comment by nelstrom** [comment]
Nice work! Thanks for a quick turnaround on this issue.

**Comment by Sannis** [comment]
It will be merged into tav/master if there is no other opinions.

**Comment by Sannis** [comment]
Released.

**Comment by nelstrom** [comment]
Great news, thanks!
